### ISSUE TITLE
Bug in 1.0.6 with unrestricted access

### ISSUE THREAD

**Issue by Darkbluetest** [nuthrash/obsidian-html-plugin#6] opened 2022-11-24 11:14 UTC
Hello

Thanks a lot for this update that allows to choose the level of sanitizing!! That really helps (it is a solution!) for some pages! There are two bugs, though:

1. Not important: in the settings, when in dark mode, some part of the table and some phrases are still rendered with white background which makes them difficult to read. This is just aesthetic.
2. This is more important: Obsidian can now show a tweet saved with SingleFile (through [ThreadReader](https://threadreaderapp.com/) website), and the video plays well, but when you click on the tweet text (the text just above or below the video) it opens the tweet in the default browser, which is fine, only that it opens it repeated in 20 tabs or so ! When you open the very same file directly in the default brower by clicking on it in the windows explorer, it opens it, and if then you click on the tweet text it opens the tweet in twitter just once, as it should. This is in unrestriced mode, otherwise the click on the text is disabled. The attached file is for testing, and normally there is no need to go full unrestriced with it, but for other entries, it is.

Thank you!

[TRB - ❝ 𝐘𝐚𝐲𝐚 ❞ FULL_.zip](https://github.com/nuthrash/obsidian-html-plugin/files/10083863/TRB.-.FULL_.zip)

**Comment by nuthrash** [comment] 2022-11-24 12:45
>  when you click on the tweet text (the text just above or below the video) it opens the tweet in the default browser, which is fine, only that it opens it repeated in 20 tabs or so !

Sorry, I cannot reproduce this situation on my PC.
Tested Platform: Obsidian 1.0.3, Chrome 105, Firefox 107 on Windows 11 22H2
Tested Modes: Unrestricted Mode, Low Restricted Mode, Balance Mode, High Restricted Mode.

The "Tweet" text block contains a hyperlink `https://twitter.com/intent/tweet?text=Thread%20by%20@__panicmoonwalk%20on%20Thread%20Reader%20App&amp;url=https%3A%2F%2Fthreadreaderapp.com%2Fthread%2F1590756028760850432.html`.
As you can see, it just pass the hyperlink to the default browser of your system, then the browser would open link. 

The complete HTML tag code is `<a class="btn btn-outline-primary share-twitter gaClickEvent" target=_blank href="https://twitter.com/intent/tweet?text=Thread%20by%20@__panicmoonwalk%20on%20Thread%20Reader%20App&amp;url=https%3A%2F%2Fthreadreaderapp.com%2Fthread%2F1590756028760850432.html" data-category=sharebuttons data-action=share-on-twitter data-label><i class="fab fa-twitter"></i> <span class=txt>Tweet</span></a>`.

I think you can paste the hyperlink address text from the address bar of the default browser when the situation happened, to let me see.
Or, you can copy the hyperlink `https://twitter.com/intent/tweet?text=Thread%20by%20@__panicmoonwalk%20on%20Thread%20Reader%20App&amp;url=https%3A%2F%2Fthreadreaderapp.com%2Fthread%2F1590756028760850432.html` to your default browser and "goto" this link to see if the same situation happen or not.

**Comment by Darkbluetest** [comment] 2022-11-24 16:57
Hi,

I am testing it now in other PC, with other Obsidian installation *although the same version(, and I can-t reproduce neither the problem. Don't know why. I3ll try to test what you say tomorrow in the first computer.

BTW, when in urestricted mode, if you change the color (dark, light mode), most of the text of Obsidian settings window is not visible, it seems a secondary effect of unrestricted mode. There is no need to open a note or nothing, just set unrestricted, go to Appearance, and change from dark to light. 

Thanks

Thanks

**Comment by nuthrash** [comment] 2022-11-25 00:04
> BTW, when in urestricted mode, if you change the color (dark, light mode), most of the text of Obsidian settings window is not visible, it seems a secondary effect of unrestricted mode. There is no need to open a note or nothing, just set unrestricted, go to Appearance, and change from dark to light.

Oh, I think you misunderstand the meaning of "**Unrestricted Mode**", it means the content of HTML files would affect other parts of Obsidian, so <ins> **this mode is unrestricted for all bad guys and good guys** </ins>! Please at least switch to "**Low Restricted Mode**" for normal usage.

I must point out there are many warning messages in README.md, the most important part is
> **Unrestricted Mode** - This mode is <ins> **very dangerous** and may cause the Obsidian app crash or disarrange layouts, **THE OBSIDIAN AND THIS PLUGIN CANNOT ASSUME RESPONSIBILITY OR LIABILITY FOR SWITCHING TO THIS MODE** </ins>. It would not sanitize anything, all elements and their content would be keeped. The Obsidian app itself might adjust something. The external script files may not executable due to Obsidian's limitation.

<hr />

When there is no file opened on Unrestricted Mode in the beginning of the Obsidian run: 
Fig.1 Unrestricted Mode in Dark 1
![Unrestricted Mode in Dark 1](https://user-images.githubusercontent.com/43021861/203874918-2d7531c4-d152-4471-90a6-0e43ee699c4a.jpg)

Everything seems good.

But after open the "TRB - ❝ 𝐘𝐚𝐲𝐚 ❞ FULL .html", you can see the situation occurred :
Fig2. Unrestricted Mode in Dark 2 - polluted by CSS styling
![Unrestricted Mode in Dark 2 - polluted by CSS styling](https://user-images.githubusercontent.com/43021861/203875382-201b30ec-c92e-4b5c-8f30-c282f976fee0.jpg)

This is caused by the CSS styles of the HTML file  "TRB - ❝ 𝐘𝐚𝐲𝐚 ❞ FULL .html". Again, I must point out there are explanations about CSS styles, the most important part is:
> **Isolated** - The CSS styles of HTML files shall be isolated against with other parts of Obsidian, otherwise the Obsidian's layouts might be disarranged at **Unrestricted Mode**.

<hr />

The CSS isolation would be applied on other modes, look this:
Fig.3 Low Restricted Mode in Dark 1
![Low Restricted Mode in Dark 1](https://user-images.githubusercontent.com/43021861/203875701-32e47ec5-1cb2-40bd-ab7f-28b2032e8aec.jpg)

You can compare the difference between "Low Restricted Mode" and "Unrestricted Mode" after open the same file.

Please at least switch to "**Low Restricted Mode**" for normal usage.
Please at least switch to "**Low Restricted Mode**" for normal usage.
Please at least switch to "**Low Restricted Mode**" for normal usage.

**Comment by Darkbluetest** [comment] 2022-12-02 09:06
Sorry for silence, I was busy with other aspects.
I'll use Low Restriction Mode by default. And yes, you have reason, what you show is inline with what I see, but with the exception of the settings page, I still see the white background issue:

![image](https://user-images.githubusercontent.com/48590261/205256520-90272740-4b8d-4b89-bf48-b7874c8a75d6.png)

**Comment by nuthrash** [comment] 2022-12-03 13:06
> Sorry for silence, I was busy with other aspects. I'll use Low Restriction Mode by default. And yes, you have reason, what you show is inline with what I see, but with the exception of the settings page, I still see the white background issue:
> 
> ![image](https://user-images.githubusercontent.com/48590261/205256520-90272740-4b8d-4b89-bf48-b7874c8a75d6.png)

This bug will be fixed at next version, you can refer the "Fig.3 Low Restricted Mode in Dark 1" above. Thanks for your report.

**Closed** 2023-01-08 06:09 UTC
